/*
Copyright Google 2025

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	context "context"

	checkpointinggkeiov1 "gke-internal.googlesource.com/gke-storage/high-scale-checkpointing/apis/checkpointing.gke.io/v1"
	scheme "gke-internal.googlesource.com/gke-storage/high-scale-checkpointing/lib/client/clientset/versioned/scheme"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// CheckpointConfigurationsGetter has a method to return a CheckpointConfigurationInterface.
// A group's client should implement this interface.
type CheckpointConfigurationsGetter interface {
	CheckpointConfigurations(namespace string) CheckpointConfigurationInterface
}

// CheckpointConfigurationInterface has methods to work with CheckpointConfiguration resources.
type CheckpointConfigurationInterface interface {
	Create(ctx context.Context, checkpointConfiguration *checkpointinggkeiov1.CheckpointConfiguration, opts metav1.CreateOptions) (*checkpointinggkeiov1.CheckpointConfiguration, error)
	Update(ctx context.Context, checkpointConfiguration *checkpointinggkeiov1.CheckpointConfiguration, opts metav1.UpdateOptions) (*checkpointinggkeiov1.CheckpointConfiguration, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, checkpointConfiguration *checkpointinggkeiov1.CheckpointConfiguration, opts metav1.UpdateOptions) (*checkpointinggkeiov1.CheckpointConfiguration, error)
	Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error
	Get(ctx context.Context, name string, opts metav1.GetOptions) (*checkpointinggkeiov1.CheckpointConfiguration, error)
	List(ctx context.Context, opts metav1.ListOptions) (*checkpointinggkeiov1.CheckpointConfigurationList, error)
	Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *checkpointinggkeiov1.CheckpointConfiguration, err error)
	CheckpointConfigurationExpansion
}

// checkpointConfigurations implements CheckpointConfigurationInterface
type checkpointConfigurations struct {
	*gentype.ClientWithList[*checkpointinggkeiov1.CheckpointConfiguration, *checkpointinggkeiov1.CheckpointConfigurationList]
}

// newCheckpointConfigurations returns a CheckpointConfigurations
func newCheckpointConfigurations(c *CheckpointingV1Client, namespace string) *checkpointConfigurations {
	return &checkpointConfigurations{
		gentype.NewClientWithList[*checkpointinggkeiov1.CheckpointConfiguration, *checkpointinggkeiov1.CheckpointConfigurationList](
			"checkpointconfigurations",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *checkpointinggkeiov1.CheckpointConfiguration {
				return &checkpointinggkeiov1.CheckpointConfiguration{}
			},
			func() *checkpointinggkeiov1.CheckpointConfigurationList {
				return &checkpointinggkeiov1.CheckpointConfigurationList{}
			},
		),
	}
}
